
import * as XLSX from 'xlsx';
import { supabase } from './lib/supabase.js';
import { PROGRAM_STATUSES, AGENDA_STATUSES, STUDENT_STATUSES, PROBLEM_STATUSES, CATEGORIES, SUBCATEGORIES, TABLES, listRows, getById, saveRow, deleteRow, count, logStage3, uploadRelatedDocument, downloadDocument } from './lib/stage3.js';

export const STAGE3_PAGES=['program-tahunan','program-semester','agenda','jadwal','konseli','permasalahan'];

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const writable=ctx=>['administrator','guru_bk'].includes(ctx.profile?.role);
const v=(o,k)=>esc(o?.[k]??'');
const toast=m=>{const x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2500)};
const ask=m=>window.confirm(m||'Apakah Anda yakin ingin menghapus data ini?');

function el(tag,attrs={},children=[]){
 const e=document.createElement(tag);
 Object.entries(attrs).forEach(([k,val])=>{if(k==='class')e.className=val;else if(k==='text')e.textContent=val;else if(k.startsWith('on'))e.addEventListener(k.slice(2),val);else e.setAttribute(k,val)});
 children.flat().filter(Boolean).forEach(c=>e.append(c.nodeType?c:document.createTextNode(String(c))));
 return e;
}
function pageBox(ctx,kicker,title,desc){
 const root=el('section',{class:'page'});
 const h=el('div',{class:'page-heading'},[el('div',{},[el('p',{class:'eyebrow',text:kicker}),el('h1',{text:title}),el('p',{text:desc})])]);
 root.append(h);return root;
}
function button(text,cls,fn){return el('button',{class:cls||'secondary',text,onClick:fn})}
function field(label,name,value='',type='text',required=false){
 const l=el('label',{});
 l.append(el('span',{text:label}));
 const i=el('input',{name,type,value:value??''});if(required)i.required=true;l.append(i);return l;
}
function area(label,name,value=''){
 const l=el('label',{class:'span-2'});l.append(el('span',{text:label}));l.append(el('textarea',{name,rows:'3'},[value??'']));return l;
}
function selectField(label,name,options,value=''){
 const l=el('label',{});l.append(el('span',{text:label}));const s=el('select',{name});s.append(el('option',{value:'',text:'Pilih...'}));options.forEach(x=>{const o=el('option',{value:x,text:x});if(x===value)o.selected=true;s.append(o)});l.append(s);return l;
}
function formShell(title,fields,onSubmit){
 const back=el('div',{class:'modal-backdrop'}),box=el('div',{class:'modal'}),head=el('div',{class:'modal-head'},[el('h2',{text:title}),button('✕','icon-btn',()=>back.remove())]),body=el('div',{class:'modal-body'}),form=el('form',{class:'form-grid'});
 fields.forEach(f=>form.append(f));
 const actions=el('div',{class:'form-actions span-2'},[button('Batal','secondary',()=>back.remove()),button('Simpan','primary',()=>form.requestSubmit())]);form.append(actions);form.onsubmit=async e=>{e.preventDefault();await onSubmit(new FormData(form),back)};body.append(form);box.append(head,body);back.append(box);document.body.append(back);
}
function privacy(){return el('div',{class:'privacy-note',text:'🔒 Data konseli dan informasi permasalahan siswa merupakan data yang bersifat rahasia dan digunakan hanya untuk kepentingan pelayanan Bimbingan dan Konseling.'});}
function tablePanel(headers,rows,empty='Belum ada data.'){
 const panel=el('div',{class:'panel table-wrap'}),t=el('table'),thead=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',{text:h})));thead.append(tr);const tb=el('tbody');
 if(!rows.length){const r=el('tr'),c=el('td',{colspan:String(headers.length),class:'table-empty',text:empty});r.append(c);tb.append(r)}else rows.forEach(r=>tb.append(r));t.append(thead,tb);panel.append(t);return panel;
}
function toolbar(ctx,placeholder,controls,onSearch){
 const bar=el('div',{class:'toolbar'}),s=el('input',{class:'field',placeholder,value:ctx.__s||''});s.oninput=()=>{clearTimeout(ctx.__timer);ctx.__s=s.value;ctx.__timer=setTimeout(onSearch,300)};bar.append(s);controls.forEach(c=>bar.append(c));return bar;
}
function exportExcel(rows,name,ctx){if(!rows.length){toast('Tidak ada data untuk diekspor.');return}const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Data');XLSX.writeFile(wb,name+'.xlsx');logStage3(ctx.session.user.id,'Export laporan','Export',name);}
function template(kind){const cols={student:['NIS','NISN','Nama Lengkap','Jenis Kelamin','Tempat Lahir','Tanggal Lahir','Kelas','Alamat','Nama Ayah','Nama Ibu','Nama Wali','Nomor HP Orang Tua'],annual:['Tahun Pelajaran','Nama Program','Bidang Layanan','Jenis Layanan','Sasaran','Kelas','Tujuan','Materi','Kegiatan','Metode','Media','Waktu Pelaksanaan','Alokasi Waktu','Penanggung Jawab','Indikator Keberhasilan','Status Pelaksanaan','Hasil','Tindak Lanjut','Keterangan'],semester:['Tahun Pelajaran','Semester','Bulan','Nama Program','Bidang Layanan','Jenis Layanan','Sasaran','Kelas','Tujuan','Materi','Kegiatan','Metode','Media','Waktu','Alokasi Waktu','Indikator Keberhasilan','Status','Hasil','Tindak Lanjut'],problem:['Nama Siswa','Tanggal','Kategori','Subkategori','Uraian','Sumber Informasi','Tingkat','Prioritas','Tindakan Awal','Tindak Lanjut','Status']}[kind];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([cols]),'Template');XLSX.writeFile(wb,'Template_'+kind+'.xlsx');}

async function uploadDialog(ctx,module,recordId){
 formShell('Upload Dokumen',[field('Judul','title',''),selectField('Kategori','category',['Profil','Program','Konseli','Asesmen','Pelayanan','Pengembangan Diri','Pelaporan','Evaluasi','Lainnya'],'Program'),(()=>{const l=el('label',{class:'span-2'});l.append(el('span',{text:'File'}),el('input',{name:'file',type:'file',accept:'.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.mp4,.mp3'}));return l})()],async(f,b)=>{
 try{const d=await uploadRelatedDocument({userId:ctx.session.user.id,title:f.get('title'),file:f.get('file'),category:f.get('category'),relatedModule:module,relatedRecordId:recordId});await logStage3(ctx.session.user.id,'Upload dokumen','Dokumen','Dokumen diunggah: '+d.file_name,d.id);b.remove();toast('Dokumen berhasil diunggah.');ctx.refresh()}catch(e){toast(e.message)}
 });
}
async function crudDelete(ctx,table,id,module){if(!writable(ctx)||!ask())return;try{await deleteRow(table,id);await logStage3(ctx.session.user.id,'Hapus data',module,'Data dihapus.',id);toast('Data berhasil dihapus.');ctx.refresh()}catch(e){toast(e.message)}}

async function programForm(ctx,type,id){
 const annual=type==='annual', existing=ctx.__rows.find(x=>x.id===id)||{}, annuals=ctx.__annual||[];
 const f=[field('Tahun Pelajaran','academic_year',existing.academic_year||'2026/2027','text',true)];
 if(!annual)f.push(selectField('Program Tahunan','annual_program_id',annuals.map(x=>x.id),existing.annual_program_id||''),selectField('Semester','semester',['Semester Ganjil','Semester Genap'],existing.semester||''),field('Bulan','month',existing.month||''));
 f.push(field('Nama Program','program_name',existing.program_name||'','text',true),selectField('Bidang Layanan','service_area',['Pribadi','Sosial','Belajar','Karier'],existing.service_area||''),selectField('Jenis Layanan','service_type',['Bimbingan Klasikal','Bimbingan Kelompok','Konseling Individual','Konseling Kelompok','Konsultasi','Referal','Layanan Informasi','Lainnya'],existing.service_type||''),field('Sasaran','target',existing.target||''),selectField('Kelas','class_level',['VII','VIII','IX','VII-IX'],existing.class_level||''),area('Tujuan','objective',existing.objective),area('Materi','material',existing.material),area('Kegiatan','activity',existing.activity),area('Metode','method',existing.method),area('Media','media',existing.media),field('Waktu Pelaksanaan','schedule',existing.schedule||''),field('Alokasi Waktu','duration',existing.duration||''),field('Penanggung Jawab','person_in_charge',existing.person_in_charge||ctx.counselor?.full_name||''),area('Indikator Keberhasilan','success_indicator',existing.success_indicator),selectField('Status Pelaksanaan','realization_status',PROGRAM_STATUSES,existing.realization_status||'Belum Dilaksanakan'),field('Tanggal Realisasi','realization_date',existing.realization_date||'','date'),area('Hasil','result',existing.result),area('Tindak Lanjut','follow_up',existing.follow_up),area('Keterangan','notes',existing.notes));
 if(!annual){setTimeout(()=>{const s=document.querySelector('.modal select[name="annual_program_id"]');if(s){[...s.options].forEach(o=>{const a=annuals.find(x=>x.id===o.value);if(a)o.textContent=a.program_name+' — '+a.academic_year});s.onchange=()=>{const a=annuals.find(x=>x.id===s.value);if(!a)return;const f=document.querySelector('.modal form');['academic_year','program_name','service_area','service_type','target','class_level','objective','material','activity','method','media','schedule','duration','success_indicator'].forEach(k=>{if(f.elements[k]&&a[k]!=null)f.elements[k].value=a[k]||''});toast('Data dasar Program Tahunan telah disalin.');};}},0)};formShell((id?'Edit ':'Tambah ')+(annual?'Program Tahunan':'Program Semester'),f,async(fd,b)=>{try{const p=Object.fromEntries(fd);p.created_by=ctx.session.user.id;p.counselor_id=ctx.counselorId;if(annual){p.school_id=ctx.school?.id||null}else{p.annual_program_id=p.annual_program_id||null}const s=await saveRow(annual?TABLES.annual:TABLES.semester,p,id);await logStage3(ctx.session.user.id,id?'Edit data':'Tambah data',annual?'Program Tahunan':'Program Semester','Data program diperbarui.',s.id);b.remove();toast('Data berhasil disimpan.');ctx.refresh()}catch(e){toast(e.message)}})
}
async function programPage(ctx,type){
 const annual=type==='annual',table=annual?TABLES.annual:TABLES.semester,rs=await listRows(table,{search:ctx.__s||'',filters:ctx.__filters||{}});ctx.__rows=rs;if(!annual)ctx.__annual=await listRows(TABLES.annual,{limit:1000});
 const box=pageBox(ctx,'PROGRAM',annual?'Program Tahunan':'Program Semester','Data program tersimpan di database.');
 if(writable(ctx))box.querySelector('.page-heading').firstElementChild.parentElement.append(button('+ Tambah Program','primary',()=>programForm(ctx,type)));
 const controls=[selectField('','fyear',[...new Set(rs.map(x=>x.academic_year).filter(Boolean))],ctx.__filters?.academic_year||''),selectField('','fstatus',PROGRAM_STATUSES,ctx.__filters?.realization_status||''),button('Export Excel','secondary',()=>exportExcel(rs,annual?'program-tahunan':'program-semester',ctx)),button('Cetak','secondary',()=>window.print())];
 controls.forEach(c=>{if(c.tagName==='SELECT')c.onchange=()=>{ctx.__filters=ctx.__filters||{};ctx.__filters[c.name==='fyear'?'academic_year':'realization_status']=c.value;ctx.refresh()}});box.append(toolbar(ctx,'Cari nama program...',controls,ctx.refresh));
 const trs=rs.map((r,i)=>{const tr=el('tr');[i+1,r.program_name,(r.service_area||''),(r.target||''),(r.schedule||''),(r.realization_status||'')].forEach(x=>tr.append(el('td',{text:x})));const a=el('td');a.append(button('Detail','secondary',()=>showRecord(ctx,table,r)),button('Edit','secondary',()=>programForm(ctx,type,r.id)),button('Hapus','secondary',()=>crudDelete(ctx,table,r.id,annual?'Program Tahunan':'Program Semester')),button('Lampiran','secondary',()=>uploadDialog(ctx,annual?'Program Tahunan':'Program Semester',r.id)));tr.append(a);return tr});
 box.append(tablePanel(['No','Program','Bidang','Sasaran','Waktu','Status','Aksi'],trs,annual?'Belum ada Program Tahunan.':'Belum ada Program Semester.'));return box;
}
function showRecord(ctx,table,r){const b=document.createElement('div');Object.entries(r).filter(([k])=>!['id','created_at','updated_at'].includes(k)).forEach(([k,v])=>b.append(el('p',{},[el('b',{text:k+': '}),String(v??'')])));formShell('Detail Data',[el('div',{class:'span-2'},[b])],async(_,m)=>m.remove())}
async function agendaPage(ctx){
 const rs=await listRows(TABLES.agenda,{search:ctx.__s||'',filters:ctx.__filters||{}});ctx.__rows=rs;const box=pageBox(ctx,'PROGRAM','Agenda Kerja Konselor','Daftar kegiatan konselor.');if(writable(ctx))box.querySelector('.page-heading').firstElementChild.parentElement.append(button('+ Tambah Agenda','primary',()=>agendaForm(ctx)));
 const controls=[selectField('','fstatus',AGENDA_STATUSES,ctx.__filters?.status||''),selectField('','fcat',['Administrasi BK','Konseling','Bimbingan','Asesmen','Kunjungan Rumah','Koordinasi','Rapat','Pengembangan Diri','Pelaporan','Evaluasi','Lainnya'],ctx.__filters?.category||''),button('Export Excel','secondary',()=>exportExcel(rs,'agenda-konselor',ctx))];controls.forEach(c=>{if(c.tagName==='SELECT')c.onchange=()=>{ctx.__filters=ctx.__filters||{};ctx.__filters[c.name==='fstatus'?'status':'category']=c.value;ctx.refresh()}});box.append(toolbar(ctx,'Cari kegiatan...',controls,ctx.refresh));
 const trs=rs.map((r,i)=>{const tr=el('tr');[i+1,r.date,(r.start_time||'')+'–'+(r.end_time||''),r.activity,r.target,r.location,r.status].forEach(x=>tr.append(el('td',{text:x})));const a=el('td');a.append(button('Edit','secondary',()=>agendaForm(ctx,r.id)),button('Hapus','secondary',()=>crudDelete(ctx,TABLES.agenda,r.id,'Agenda')),button('Lampiran','secondary',()=>uploadDialog(ctx,'Agenda',r.id)));tr.append(a);return tr});box.append(tablePanel(['No','Tanggal','Jam','Kegiatan','Sasaran','Tempat','Status','Aksi'],trs,'Belum ada Agenda Kerja Konselor.'));return box;
}
async function agendaForm(ctx,id){const d=ctx.__rows?.find(x=>x.id===id)||{};formShell((id?'Edit ':'Tambah ')+'Agenda Kerja Konselor',[field('Tanggal','date',d.date||new Date().toISOString().slice(0,10),'date',true),field('Jam Mulai','start_time',(d.start_time||'').slice(0,5),'time'),field('Jam Selesai','end_time',(d.end_time||'').slice(0,5),'time'),field('Kegiatan','activity',d.activity||'','text',true),selectField('Kategori','category',['Administrasi BK','Konseling','Bimbingan','Asesmen','Kunjungan Rumah','Koordinasi','Rapat','Pengembangan Diri','Pelaporan','Evaluasi','Lainnya'],d.category||''),field('Sasaran','target',d.target),field('Kelas','class_level',d.class_level),field('Tempat','location',d.location),area('Tujuan','objective',d.objective),area('Hasil','result',d.result),area('Tindak Lanjut','follow_up',d.follow_up),selectField('Status','status',AGENDA_STATUSES,d.status||'Direncanakan'),area('Keterangan','notes',d.notes)],async(fd,b)=>{try{const p=Object.fromEntries(fd);p.counselor_id=ctx.counselorId;const s=await saveRow(TABLES.agenda,p,id);await logStage3(ctx.session.user.id,id?'Edit data':'Tambah data','Agenda','Agenda diperbarui.',s.id);b.remove();ctx.refresh()}catch(e){toast(e.message)}})}
function scheduleForm(ctx,kind,id){const table=TABLES[kind],d=ctx.__rows?.find(x=>x.id===id)||{},fs=[];if(kind==='weekly')fs.push(selectField('Hari','day_of_week',['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'],d.day_of_week||''));else fs.push(field('Tanggal','date',d.date||new Date().toISOString().slice(0,10),'date',true));fs.push(field('Jam Mulai','start_time',(d.start_time||'').slice(0,5),'time'),field('Jam Selesai','end_time',(d.end_time||'').slice(0,5),'time'),field('Kegiatan','activity',d.activity||'','text',true),field('Kelas','class_level',d.class_level),field('Sasaran','target',d.target),selectField('Jenis Layanan','service_type',['Bimbingan Klasikal','Bimbingan Kelompok','Konseling Individual','Konseling Kelompok','Konsultasi','Referal','Lainnya'],d.service_type||''),field('Tempat','location',d.location),kind==='daily'?selectField('Status','status',AGENDA_STATUSES,d.status||'Direncanakan'):area('Keterangan','notes',d.notes));formShell((id?'Edit ':'Tambah ')+(kind==='weekly'?'Program Mingguan':'Program Harian'),fs,async(fd,b)=>{try{const p=Object.fromEntries(fd);p.counselor_id=ctx.counselorId;const s=await saveRow(table,p,id);await logStage3(ctx.session.user.id,id?'Edit data':'Tambah data',kind==='weekly'?'Jadwal Mingguan':'Jadwal Harian','Jadwal diperbarui.',s.id);b.remove();ctx.refresh()}catch(e){toast(e.message)}})}
async function schedulesPage(ctx){const w=await listRows(TABLES.weekly,{limit:500}),d=await listRows(TABLES.daily,{limit:500});ctx.__rows=w;const box=pageBox(ctx,'PROGRAM','Jadwal Kegiatan Konselor','Program mingguan dan harian.');for(const [kind,label,data] of [['weekly','Program Mingguan',w],['daily','Program Harian',d]]){const p=el('div',{class:'panel schedule-panel'}),head=el('div',{class:'panel-head'},[el('h3',{text:label})]);if(writable(ctx))head.append(button('+ Tambah','primary',()=>scheduleForm(ctx,kind)));p.append(head);const trs=data.map(r=>{const tr=el('tr');[kind==='weekly'?r.day_of_week:r.date,(r.start_time||'')+'–'+(r.end_time||''),r.activity,r.class_level,r.target,r.status||r.service_type].forEach(x=>tr.append(el('td',{text:x})));const a=el('td');a.append(button('Edit','secondary',()=>scheduleForm(ctx,kind,r.id)),button('Hapus','secondary',()=>crudDelete(ctx,TABLES[kind],r.id,label)));tr.append(a);return tr});p.append(tablePanel(['Hari/Tanggal','Jam','Kegiatan','Kelas','Sasaran','Status/Layanan','Aksi'],trs,'Belum ada jadwal.'));box.append(p)}return box}

function studentForm(ctx,id){const d=ctx.__rows?.find(x=>x.id===id)||{};formShell((id?'Edit ':'Tambah ')+'Konseli',[field('NIS','nis',d.nis),field('NISN','nisn',d.nisn),field('Nama Lengkap','full_name',d.full_name,'text',true),selectField('Jenis Kelamin','gender',['L','P'],d.gender||''),field('Tempat Lahir','birth_place',d.birth_place),field('Tanggal Lahir','birth_date',d.birth_date,'date'),selectField('Kelas','class_name',['VII','VIII','IX'],d.class_name||''),field('Nomor HP','phone',d.phone),area('Alamat','address',d.address),field('Nama Ayah','father_name',d.father_name),field('Nama Ibu','mother_name',d.mother_name),field('Nama Wali','guardian_name',d.guardian_name),field('Nomor HP Orang Tua/Wali','parent_phone',d.parent_phone),area('Alamat Orang Tua/Wali','guardian_address',d.guardian_address),selectField('Status Siswa','student_status',STUDENT_STATUSES,d.student_status||'Aktif'),area('Catatan Umum','notes',d.notes)],async(fd,b)=>{try{const p=Object.fromEntries(fd);p.counselor_id=ctx.counselorId;if(!p.full_name)throw new Error('Nama Lengkap wajib diisi.');const s=await saveRow(TABLES.students,p,id);await logStage3(ctx.session.user.id,id?'Edit data':'Tambah data','Konseli','Data konseli diperbarui.',s.id);b.remove();ctx.refresh()}catch(e){toast(e.message.includes('duplicate')?'NIS/NISN sudah terdaftar.':e.message)}})}
async function studentsPage(ctx){const rs=await listRows(TABLES.students,{search:ctx.__s||'',filters:ctx.__filters||{}});ctx.__rows=rs;const box=pageBox(ctx,'KEGIATAN PELAYANAN','Daftar Konseli / Siswa Asuh','CONFIDENTIAL — akses dibatasi sesuai role.');box.append(privacy());if(writable(ctx))box.querySelector('.page-heading').firstElementChild.parentElement.append(button('+ Tambah Konseli','primary',()=>studentForm(ctx)));const ctr=[selectField('','fclass',['VII','VIII','IX'],ctx.__filters?.class_name||''),selectField('','fgender',['L','P'],ctx.__filters?.gender||''),selectField('','fstatus',STUDENT_STATUSES,ctx.__filters?.student_status||''),button('Import Excel','secondary',()=>importStudents(ctx)),button('Template Excel','secondary',()=>template('student')),button('Export Excel','secondary',()=>exportExcel(rs,'daftar-konseli',ctx)),button('Cetak','secondary',()=>window.print())];ctr.forEach(c=>{if(c.tagName==='SELECT')c.onchange=()=>{ctx.__filters=ctx.__filters||{};ctx.__filters[c.name.slice(1)]=c.value;ctx.refresh()}});box.append(toolbar(ctx,'Cari nama, NIS atau NISN...',ctr,ctx.refresh));const trs=rs.map((r,i)=>{const tr=el('tr');[i+1,r.nisn,r.full_name,r.gender,r.class_name,r.parent_name||r.guardian_name,r.student_status].forEach(x=>tr.append(el('td',{text:x})));const a=el('td');a.append(button('Detail','secondary',()=>studentDetail(ctx,r.id)),button('Edit','secondary',()=>studentForm(ctx,r.id)),button('Hapus','secondary',()=>crudDelete(ctx,TABLES.students,r.id,'Konseli')),button('Dokumen','secondary',()=>uploadDialog(ctx,'Konseli',r.id)));tr.append(a);return tr});box.append(tablePanel(['No','NISN','Nama','L/P','Kelas','Orang Tua/Wali','Status','Aksi'],trs,'Belum ada data konseli.'));return box}
async function studentDetail(ctx,id){const s=await getById(TABLES.students,id),p=await supabase.from(TABLES.problems).select('*').eq('student_id',id).order('date',{ascending:false}),d=await supabase.from('documents').select('*').eq('related_module','Konseli').eq('related_record_id',id);const box=pageBox(ctx,'CONFIDENTIAL','Profil Konseli',(s.full_name||'')+' · '+(s.class_name||''));box.append(button('Kembali','secondary',()=>ctx.go('konseli')),privacy());const hero=el('div',{class:'student-hero'},[el('div',{class:'avatar xl',text:(s.full_name||'S').slice(0,2).toUpperCase()}),el('div',{},[el('h2',{text:s.full_name}),el('p',{text:'NISN: '+(s.nisn||'-')+' · Kelas: '+(s.class_name||'-')+' · Status: '+(s.student_status||'-')})])]);box.append(hero);const tabs=el('div',{class:'tabbar'});['Profil','Kebutuhan & Permasalahan ('+(p.data?.length||0)+')','Layanan BK','Asesmen','Kunjungan Rumah','Catatan Anekdot','Dokumen ('+(d.data?.length||0)+')','Riwayat Aktivitas'].forEach(x=>tabs.append(el('button',{text:x})));box.append(tabs);const info=el('div',{class:'panel profile-grid'});[['NIS',s.nis],['NISN',s.nisn],['Jenis Kelamin',s.gender],['Tempat/Tanggal Lahir',(s.birth_place||'')+' '+(s.birth_date||'')],['Ayah/Ibu',(s.father_name||'')+' / '+(s.mother_name||'')],['Wali',s.guardian_name],['Telepon',s.parent_phone],['Alamat',s.address]].forEach(x=>info.append(el('div',{},[el('span',{text:x[0]}),el('b',{text:x[1]||'-'})])));box.append(info);Array.from(tabs.children).forEach((b,i)=>b.onclick=()=>{Array.from(tabs.children).forEach(x=>x.classList.remove('active'));b.classList.add('active');if(i===0){ctx.refresh()}else{info.innerHTML='';info.append(el('div',{class:'empty-state',text:'Belum ada data pada tahap ini.'}))}});return box}

function problemForm(ctx,id){const d=ctx.__rows?.find(x=>x.id===id)||{},students=ctx.__students||[];formShell((id?'Edit ':'Tambah ')+'Kebutuhan / Permasalahan',[selectField('Nama Siswa','student_id',students.map(x=>x.id),d.student_id||''),field('Tanggal','date',d.date||new Date().toISOString().slice(0,10),'date',true),selectField('Kategori','category',CATEGORIES,d.category||''),selectField('Subkategori','sub_category',SUBCATEGORIES[d.category]||[],d.sub_category||''),area('Uraian Kebutuhan/Permasalahan','description',d.description),selectField('Sumber Informasi','source_of_information',['Siswa','Orang tua','Guru mata pelajaran','Wali kelas','Guru BK','Teman sebaya','Hasil asesmen','Observasi','Lainnya'],d.source_of_information||''),selectField('Tingkat','severity',['Rendah','Sedang','Tinggi'],d.severity||''),selectField('Prioritas','priority',['Rendah','Sedang','Tinggi'],d.priority||''),area('Tindakan Awal','initial_action',d.initial_action),area('Rencana Tindak Lanjut','follow_up',d.follow_up),selectField('Status','status',PROBLEM_STATUSES,d.status||'Baru'),area('Catatan','notes',d.notes)],async(fd,b)=>{try{const p=Object.fromEntries(fd);p.counselor_id=ctx.counselorId;p.confidentiality_level='CONFIDENTIAL';if(!p.student_id||!p.description)throw new Error('Siswa dan uraian permasalahan wajib diisi.');const s=await saveRow(TABLES.problems,p,id);await logStage3(ctx.session.user.id,id?'Edit data':'Tambah data','Kebutuhan & Permasalahan','Data kebutuhan/permasalahan diperbarui.',s.id);b.remove();ctx.refresh()}catch(e){toast(e.message)}})}
async function problemsPage(ctx){ctx.__students=await listRows(TABLES.students,{limit:2000});const rs=await listRows(TABLES.problems,{search:ctx.__s||'',filters:ctx.__filters||{}});ctx.__rows=rs;const box=pageBox(ctx,'KEGIATAN PELAYANAN','Data Kebutuhan & Permasalahan Konseli','CONFIDENTIAL — isi permasalahan tidak tampil di dashboard.');box.append(privacy());if(writable(ctx))box.querySelector('.page-heading').firstElementChild.parentElement.append(button('+ Tambah Data','primary',()=>problemForm(ctx)));const ctr=[selectField('','fcat',CATEGORIES,ctx.__filters?.category||''),selectField('','fseverity',['Rendah','Sedang','Tinggi'],ctx.__filters?.severity||''),selectField('','fpriority',['Rendah','Sedang','Tinggi'],ctx.__filters?.priority||''),selectField('','fstatus',PROBLEM_STATUSES,ctx.__filters?.status||''),button('Template Excel','secondary',()=>template('problem')),button('Export Excel','secondary',()=>exportExcel(rs,'kebutuhan-permasalahan',ctx))];ctr.forEach(c=>{if(c.tagName==='SELECT')c.onchange=()=>{ctx.__filters=ctx.__filters||{};ctx.__filters[c.name.slice(1)]=c.value;ctx.refresh()}});box.append(toolbar(ctx,'Cari kategori atau uraian...',ctr,ctx.refresh));const trs=rs.map((r,i)=>{const s=ctx.__students.find(x=>x.id===r.student_id)||{};const tr=el('tr');[i+1,r.date,s.full_name,s.class_name,r.category,r.severity,r.priority,r.status].forEach(x=>tr.append(el('td',{text:x})));const a=el('td');a.append(button('Detail','secondary',()=>showRecord(ctx,TABLES.problems,r)),button('Edit','secondary',()=>problemForm(ctx,r.id)),button('Hapus','secondary',()=>crudDelete(ctx,TABLES.problems,r.id,'Kebutuhan & Permasalahan')),button('Dokumen','secondary',()=>uploadDialog(ctx,'Kebutuhan & Permasalahan',r.id)));tr.append(a);return tr});box.append(tablePanel(['No','Tanggal','Siswa','Kelas','Kategori','Tingkat','Prioritas','Status','Aksi'],trs,'Belum ada data kebutuhan/permasalahan.'));return box}

async function importStudents(ctx){formShell('Import Data Siswa dari Excel',[(()=>{const l=el('label',{});l.append(el('span',{text:'File Excel (.xlsx/.xls)'}),el('input',{id:'excel-input',type:'file',accept:'.xlsx,.xls'}));return l})(),el('div',{id:'import-preview',class:'span-2'})],async()=>{});const inputEl=document.querySelector('#excel-input'),modalEl=inputEl.closest('.modal-backdrop');inputEl.onchange=async()=>{try{const data=XLSX.utils.sheet_to_json(XLSX.read(await inputEl.files[0].arrayBuffer(),{type:'array'}).Sheets[XLSX.read(await inputEl.files[0].arrayBuffer(),{type:'array'}).SheetNames[0]],{defval:''});document.querySelector('#import-preview').textContent=data.length+' baris ditemukan. Klik Import setelah validasi awal.';const b=button('Import Data','primary',async()=>{try{const ex=await supabase.from(TABLES.students).select('nis,nisn'),seen=new Set((ex.data||[]).flatMap(x=>[x.nis,x.nisn].filter(Boolean).map(String))),ins=data.filter(r=>!seen.has(String(r.NIS||''))&&!seen.has(String(r.NISN||''))).map(r=>({nis:r.NIS||null,nisn:r.NISN||null,full_name:r['Nama Lengkap'],gender:r['Jenis Kelamin']||null,birth_place:r['Tempat Lahir']||null,birth_date:r['Tanggal Lahir']||null,class_name:r.Kelas||null,address:r.Alamat||null,father_name:r['Nama Ayah']||null,mother_name:r['Nama Ibu']||null,guardian_name:r['Nama Wali']||null,parent_phone:r['Nomor HP Orang Tua']||null,counselor_id:ctx.counselorId}));if(ins.length){const r=await supabase.from(TABLES.students).insert(ins);if(r.error)throw r.error}await logStage3(ctx.session.user.id,'Import data','Konseli','Import Excel: '+ins.length+' siswa.');modalEl.remove();toast(ins.length+' data berhasil diimport. Duplikat dilewati.');ctx.refresh()}catch(e){toast(e.message)}});modalEl.querySelector('.form-actions').append(b)}catch(e){toast('File Excel tidak dapat dibaca.')}}}
export async function renderStage3(page,ctx){
 const root=document.querySelector('#content');root.innerHTML='';ctx.refresh=()=>renderStage3(page,ctx);ctx.go=p=>{ctx.page=p;ctx.refresh=()=>ctx.render();ctx.render()};let content;
 if(page==='program-tahunan')content=await programPage(ctx,'annual');
 else if(page==='program-semester')content=await programPage(ctx,'semester');
 else if(page==='agenda')content=await agendaPage(ctx);
 else if(page==='jadwal')content=await schedulesPage(ctx);
 else if(page==='konseli')content=await studentsPage(ctx);
 else if(page==='permasalahan')content=await problemsPage(ctx);
 if(content)root.append(content);
}
